# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pkg/proto/banner/banner.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'pkg/proto/banner/banner.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dpkg/proto/banner/banner.proto\x12\x08\x62\x61nnerpb\"{\n\x06\x42\x61nner\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0c\n\x04link\x18\x04 \x01(\t\x12\x0f\n\x07ownerID\x18\x05 \x01(\t\x12\x11\n\tmax_price\x18\x06 \x01(\t\x12\n\n\x02id\x18\x07 \x01(\x03\"5\n\x12\x42\x61nnerWithMinPrice\x12\x11\n\tmin_price\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x03\"\x1b\n\rBannerRequest\x12\n\n\x02id\x18\x01 \x01(\x03\"\"\n\rActiveBanners\x12\x11\n\tbanner_id\x18\x01 \x03(\x03\x32\xdb\x01\n\rBannerService\x12\x41\n\x0fGetRandomBanner\x12\x1c.bannerpb.BannerWithMinPrice\x1a\x10.bannerpb.Banner\x12K\n\x12GetSuitableBanners\x12\x1c.bannerpb.BannerWithMinPrice\x1a\x17.bannerpb.ActiveBanners\x12:\n\rGetBannerByID\x12\x17.bannerpb.BannerRequest\x1a\x10.bannerpb.BannerB\x1bZ\x19pkg/proto/banner;bannerpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pkg.proto.banner.banner_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\031pkg/proto/banner;bannerpb'
  _globals['_BANNER']._serialized_start=43
  _globals['_BANNER']._serialized_end=166
  _globals['_BANNERWITHMINPRICE']._serialized_start=168
  _globals['_BANNERWITHMINPRICE']._serialized_end=221
  _globals['_BANNERREQUEST']._serialized_start=223
  _globals['_BANNERREQUEST']._serialized_end=250
  _globals['_ACTIVEBANNERS']._serialized_start=252
  _globals['_ACTIVEBANNERS']._serialized_end=286
  _globals['_BANNERSERVICE']._serialized_start=289
  _globals['_BANNERSERVICE']._serialized_end=508
# @@protoc_insertion_point(module_scope)
