// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: pkg/proto/banner/banner.proto

package bannerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Banner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Link          string                 `protobuf:"bytes,4,opt,name=link,proto3" json:"link,omitempty"`
	OwnerID       string                 `protobuf:"bytes,5,opt,name=ownerID,proto3" json:"ownerID,omitempty"`
	MaxPrice      string                 `protobuf:"bytes,6,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	Id            int64                  `protobuf:"varint,7,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Banner) Reset() {
	*x = Banner{}
	mi := &file_pkg_proto_banner_banner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Banner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Banner) ProtoMessage() {}

func (x *Banner) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_banner_banner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Banner.ProtoReflect.Descriptor instead.
func (*Banner) Descriptor() ([]byte, []int) {
	return file_pkg_proto_banner_banner_proto_rawDescGZIP(), []int{0}
}

func (x *Banner) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Banner) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Banner) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Banner) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *Banner) GetOwnerID() string {
	if x != nil {
		return x.OwnerID
	}
	return ""
}

func (x *Banner) GetMaxPrice() string {
	if x != nil {
		return x.MaxPrice
	}
	return ""
}

func (x *Banner) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type BannerWithMinPrice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinPrice      string                 `protobuf:"bytes,1,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	Code          int64                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BannerWithMinPrice) Reset() {
	*x = BannerWithMinPrice{}
	mi := &file_pkg_proto_banner_banner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BannerWithMinPrice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BannerWithMinPrice) ProtoMessage() {}

func (x *BannerWithMinPrice) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_banner_banner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BannerWithMinPrice.ProtoReflect.Descriptor instead.
func (*BannerWithMinPrice) Descriptor() ([]byte, []int) {
	return file_pkg_proto_banner_banner_proto_rawDescGZIP(), []int{1}
}

func (x *BannerWithMinPrice) GetMinPrice() string {
	if x != nil {
		return x.MinPrice
	}
	return ""
}

func (x *BannerWithMinPrice) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

type BannerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BannerRequest) Reset() {
	*x = BannerRequest{}
	mi := &file_pkg_proto_banner_banner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BannerRequest) ProtoMessage() {}

func (x *BannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_banner_banner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BannerRequest.ProtoReflect.Descriptor instead.
func (*BannerRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_banner_banner_proto_rawDescGZIP(), []int{2}
}

func (x *BannerRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ActiveBanners struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BannerId      []int64                `protobuf:"varint,1,rep,packed,name=banner_id,json=bannerId,proto3" json:"banner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveBanners) Reset() {
	*x = ActiveBanners{}
	mi := &file_pkg_proto_banner_banner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveBanners) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveBanners) ProtoMessage() {}

func (x *ActiveBanners) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_banner_banner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveBanners.ProtoReflect.Descriptor instead.
func (*ActiveBanners) Descriptor() ([]byte, []int) {
	return file_pkg_proto_banner_banner_proto_rawDescGZIP(), []int{3}
}

func (x *ActiveBanners) GetBannerId() []int64 {
	if x != nil {
		return x.BannerId
	}
	return nil
}

var File_pkg_proto_banner_banner_proto protoreflect.FileDescriptor

const file_pkg_proto_banner_banner_proto_rawDesc = "" +
	"\n" +
	"\x1dpkg/proto/banner/banner.proto\x12\bbannerpb\"\xb5\x01\n" +
	"\x06Banner\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04link\x18\x04 \x01(\tR\x04link\x12\x18\n" +
	"\aownerID\x18\x05 \x01(\tR\aownerID\x12\x1b\n" +
	"\tmax_price\x18\x06 \x01(\tR\bmaxPrice\x12\x0e\n" +
	"\x02id\x18\a \x01(\x03R\x02id\"E\n" +
	"\x12BannerWithMinPrice\x12\x1b\n" +
	"\tmin_price\x18\x01 \x01(\tR\bminPrice\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x03R\x04code\"\x1f\n" +
	"\rBannerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\",\n" +
	"\rActiveBanners\x12\x1b\n" +
	"\tbanner_id\x18\x01 \x03(\x03R\bbannerId2\xdb\x01\n" +
	"\rBannerService\x12A\n" +
	"\x0fGetRandomBanner\x12\x1c.bannerpb.BannerWithMinPrice\x1a\x10.bannerpb.Banner\x12K\n" +
	"\x12GetSuitableBanners\x12\x1c.bannerpb.BannerWithMinPrice\x1a\x17.bannerpb.ActiveBanners\x12:\n" +
	"\rGetBannerByID\x12\x17.bannerpb.BannerRequest\x1a\x10.bannerpb.BannerB$Z\"retarget/pkg/proto/banner;bannerpbb\x06proto3"

var (
	file_pkg_proto_banner_banner_proto_rawDescOnce sync.Once
	file_pkg_proto_banner_banner_proto_rawDescData []byte
)

func file_pkg_proto_banner_banner_proto_rawDescGZIP() []byte {
	file_pkg_proto_banner_banner_proto_rawDescOnce.Do(func() {
		file_pkg_proto_banner_banner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_banner_banner_proto_rawDesc), len(file_pkg_proto_banner_banner_proto_rawDesc)))
	})
	return file_pkg_proto_banner_banner_proto_rawDescData
}

var file_pkg_proto_banner_banner_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_proto_banner_banner_proto_goTypes = []any{
	(*Banner)(nil),             // 0: bannerpb.Banner
	(*BannerWithMinPrice)(nil), // 1: bannerpb.BannerWithMinPrice
	(*BannerRequest)(nil),      // 2: bannerpb.BannerRequest
	(*ActiveBanners)(nil),      // 3: bannerpb.ActiveBanners
}
var file_pkg_proto_banner_banner_proto_depIdxs = []int32{
	1, // 0: bannerpb.BannerService.GetRandomBanner:input_type -> bannerpb.BannerWithMinPrice
	1, // 1: bannerpb.BannerService.GetSuitableBanners:input_type -> bannerpb.BannerWithMinPrice
	2, // 2: bannerpb.BannerService.GetBannerByID:input_type -> bannerpb.BannerRequest
	0, // 3: bannerpb.BannerService.GetRandomBanner:output_type -> bannerpb.Banner
	3, // 4: bannerpb.BannerService.GetSuitableBanners:output_type -> bannerpb.ActiveBanners
	0, // 5: bannerpb.BannerService.GetBannerByID:output_type -> bannerpb.Banner
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_banner_banner_proto_init() }
func file_pkg_proto_banner_banner_proto_init() {
	if File_pkg_proto_banner_banner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_banner_banner_proto_rawDesc), len(file_pkg_proto_banner_banner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_banner_banner_proto_goTypes,
		DependencyIndexes: file_pkg_proto_banner_banner_proto_depIdxs,
		MessageInfos:      file_pkg_proto_banner_banner_proto_msgTypes,
	}.Build()
	File_pkg_proto_banner_banner_proto = out.File
	file_pkg_proto_banner_banner_proto_goTypes = nil
	file_pkg_proto_banner_banner_proto_depIdxs = nil
}
