// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	adv "retarget/internal/adv-service/entity/adv"
)

// AdvRepositoryInterface is an autogenerated mock type for the AdvRepositoryInterface type
type AdvRepositoryInterface struct {
	mock.Mock
}

// CreateLink provides a mock function with given fields: link
func (_m *AdvRepositoryInterface) CreateLink(link adv.Link) error {
	ret := _m.Called(link)

	if len(ret) == 0 {
		panic("no return value specified for CreateLink")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(adv.Link) error); ok {
		r0 = rf(link)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteLink provides a mock function with given fields: link
func (_m *AdvRepositoryInterface) DeleteLink(link string) error {
	ret := _m.Called(link)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLink")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(link)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ... существующий код ...
