CREATE TABLE auth_user (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE CHECK (
        email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'
    ),
    password BYTEA NOT NULL,
    description TEXT,
    balance DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    created_at TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'UTC'),
    role SMALLINT NOT NULL
);

CREATE UNIQUE INDEX auth_user_username_key ON auth_user(username);
CREATE UNIQUE INDEX auth_user_email_key ON auth_user(email);

CREATE
OR REPLACE FUNCTION update_updated_at() RETURNS TRIGGER AS $ $ BEGIN NEW.updated_at = (now() AT TIME ZONE 'UTC');

RETURN NEW;

END;

$ $ LANGUAGE plpgsql;

CREATE TRIGGER update_user_updated_at BEFORE
UPDATE
    ON auth_user FOR EACH ROW EXECUTE FUNCTION update_updated_at();
