// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: pkg/proto/banner.proto

package bannerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Banner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Link          string                 `protobuf:"bytes,4,opt,name=link,proto3" json:"link,omitempty"`
	OwnerID       string                 `protobuf:"bytes,5,opt,name=ownerID,proto3" json:"ownerID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Banner) Reset() {
	*x = Banner{}
	mi := &file_pkg_proto_banner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Banner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Banner) ProtoMessage() {}

func (x *Banner) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_banner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Banner.ProtoReflect.Descriptor instead.
func (*Banner) Descriptor() ([]byte, []int) {
	return file_pkg_proto_banner_proto_rawDescGZIP(), []int{0}
}

func (x *Banner) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Banner) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Banner) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Banner) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *Banner) GetOwnerID() string {
	if x != nil {
		return x.OwnerID
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pkg_proto_banner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_banner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pkg_proto_banner_proto_rawDescGZIP(), []int{1}
}

var File_pkg_proto_banner_proto protoreflect.FileDescriptor

const file_pkg_proto_banner_proto_rawDesc = "" +
	"\n" +
	"\x16pkg/proto/banner.proto\x12\bbannerpb\"\x88\x01\n" +
	"\x06Banner\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04link\x18\x04 \x01(\tR\x04link\x12\x18\n" +
	"\aownerID\x18\x05 \x01(\tR\aownerID\"\a\n" +
	"\x05Empty2v\n" +
	"\rBannerService\x12/\n" +
	"\n" +
	"SendBanner\x12\x10.bannerpb.Banner\x1a\x0f.bannerpb.Empty\x124\n" +
	"\x0fGetRandomBanner\x12\x0f.bannerpb.Empty\x1a\x10.bannerpb.BannerB$Z\"retarget/pkg/proto/banner;bannerpbb\x06proto3"

var (
	file_pkg_proto_banner_proto_rawDescOnce sync.Once
	file_pkg_proto_banner_proto_rawDescData []byte
)

func file_pkg_proto_banner_proto_rawDescGZIP() []byte {
	file_pkg_proto_banner_proto_rawDescOnce.Do(func() {
		file_pkg_proto_banner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_banner_proto_rawDesc), len(file_pkg_proto_banner_proto_rawDesc)))
	})
	return file_pkg_proto_banner_proto_rawDescData
}

var file_pkg_proto_banner_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_banner_proto_goTypes = []any{
	(*Banner)(nil), // 0: bannerpb.Banner
	(*Empty)(nil),  // 1: bannerpb.Empty
}
var file_pkg_proto_banner_proto_depIdxs = []int32{
	0, // 0: bannerpb.BannerService.SendBanner:input_type -> bannerpb.Banner
	1, // 1: bannerpb.BannerService.GetRandomBanner:input_type -> bannerpb.Empty
	1, // 2: bannerpb.BannerService.SendBanner:output_type -> bannerpb.Empty
	0, // 3: bannerpb.BannerService.GetRandomBanner:output_type -> bannerpb.Banner
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_banner_proto_init() }
func file_pkg_proto_banner_proto_init() {
	if File_pkg_proto_banner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_banner_proto_rawDesc), len(file_pkg_proto_banner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_banner_proto_goTypes,
		DependencyIndexes: file_pkg_proto_banner_proto_depIdxs,
		MessageInfos:      file_pkg_proto_banner_proto_msgTypes,
	}.Build()
	File_pkg_proto_banner_proto = out.File
	file_pkg_proto_banner_proto_goTypes = nil
	file_pkg_proto_banner_proto_depIdxs = nil
}
