// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: pkg/proto/recommend/recommend.proto

package recommendpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	banner "pkg/proto/banner"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecommendationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlatformId    int64                  `protobuf:"varint,1,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"`
	SlotName      string                 `protobuf:"bytes,2,opt,name=slot_name,json=slotName,proto3" json:"slot_name,omitempty"`
	BannerId      []int64                `protobuf:"varint,3,rep,packed,name=banner_id,json=bannerId,proto3" json:"banner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendationRequest) Reset() {
	*x = RecommendationRequest{}
	mi := &file_pkg_proto_recommend_recommend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationRequest) ProtoMessage() {}

func (x *RecommendationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_recommend_recommend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationRequest.ProtoReflect.Descriptor instead.
func (*RecommendationRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_recommend_recommend_proto_rawDescGZIP(), []int{0}
}

func (x *RecommendationRequest) GetPlatformId() int64 {
	if x != nil {
		return x.PlatformId
	}
	return 0
}

func (x *RecommendationRequest) GetSlotName() string {
	if x != nil {
		return x.SlotName
	}
	return ""
}

func (x *RecommendationRequest) GetBannerId() []int64 {
	if x != nil {
		return x.BannerId
	}
	return nil
}

var File_pkg_proto_recommend_recommend_proto protoreflect.FileDescriptor

const file_pkg_proto_recommend_recommend_proto_rawDesc = "" +
	"\n" +
	"#pkg/proto/recommend/recommend.proto\x12\vrecommendpb\x1a\x1dpkg/proto/banner/banner.proto\"r\n" +
	"\x15RecommendationRequest\x12\x1f\n" +
	"\vplatform_id\x18\x01 \x01(\x03R\n" +
	"platformId\x12\x1b\n" +
	"\tslot_name\x18\x02 \x01(\tR\bslotName\x12\x1b\n" +
	"\tbanner_id\x18\x03 \x03(\x03R\bbannerId2_\n" +
	"\x10RecommendService\x12K\n" +
	"\x13GetBannerByMetaData\x12\".recommendpb.RecommendationRequest\x1a\x10.bannerpb.BannerB*Z(retarget/pkg/proto/recommend;recommendpbb\x06proto3"

var (
	file_pkg_proto_recommend_recommend_proto_rawDescOnce sync.Once
	file_pkg_proto_recommend_recommend_proto_rawDescData []byte
)

func file_pkg_proto_recommend_recommend_proto_rawDescGZIP() []byte {
	file_pkg_proto_recommend_recommend_proto_rawDescOnce.Do(func() {
		file_pkg_proto_recommend_recommend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_recommend_recommend_proto_rawDesc), len(file_pkg_proto_recommend_recommend_proto_rawDesc)))
	})
	return file_pkg_proto_recommend_recommend_proto_rawDescData
}

var file_pkg_proto_recommend_recommend_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_proto_recommend_recommend_proto_goTypes = []any{
	(*RecommendationRequest)(nil), // 0: recommendpb.RecommendationRequest
	(*banner.Banner)(nil),         // 1: bannerpb.Banner
}
var file_pkg_proto_recommend_recommend_proto_depIdxs = []int32{
	0, // 0: recommendpb.RecommendService.GetBannerByMetaData:input_type -> recommendpb.RecommendationRequest
	1, // 1: recommendpb.RecommendService.GetBannerByMetaData:output_type -> bannerpb.Banner
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_recommend_recommend_proto_init() }
func file_pkg_proto_recommend_recommend_proto_init() {
	if File_pkg_proto_recommend_recommend_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_recommend_recommend_proto_rawDesc), len(file_pkg_proto_recommend_recommend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_recommend_recommend_proto_goTypes,
		DependencyIndexes: file_pkg_proto_recommend_recommend_proto_depIdxs,
		MessageInfos:      file_pkg_proto_recommend_recommend_proto_msgTypes,
	}.Build()
	File_pkg_proto_recommend_recommend_proto = out.File
	file_pkg_proto_recommend_recommend_proto_goTypes = nil
	file_pkg_proto_recommend_recommend_proto_depIdxs = nil
}
