# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pkg/proto/recommend/recommend.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'pkg/proto/recommend/recommend.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pkg.proto.banner import banner_pb2 as pkg_dot_proto_dot_banner_dot_banner__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#pkg/proto/recommend/recommend.proto\x12\x0brecommendpb\x1a\x1dpkg/proto/banner/banner.proto\"R\n\x15RecommendationRequest\x12\x13\n\x0bplatform_id\x18\x01 \x01(\x03\x12\x11\n\tslot_name\x18\x02 \x01(\t\x12\x11\n\tbanner_id\x18\x03 \x03(\x03\x32_\n\x10RecommendService\x12K\n\x13GetBannerByMetaData\x12\".recommendpb.RecommendationRequest\x1a\x10.bannerpb.BannerB!Z\x1fpkg/proto/recommend;recommendpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pkg.proto.recommend.recommend_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\037pkg/proto/recommend;recommendpb'
  _globals['_RECOMMENDATIONREQUEST']._serialized_start=83
  _globals['_RECOMMENDATIONREQUEST']._serialized_end=165
  _globals['_RECOMMENDSERVICE']._serialized_start=167
  _globals['_RECOMMENDSERVICE']._serialized_end=262
# @@protoc_insertion_point(module_scope)
